language: node_js
script: 
  - yarn test
  - yarn build
deploy:
  provider: elasticbeanstalk
  access_key_id: "CXOJpVLvR3oyV26BpZ8mP6QfYBkCIUJJ/XPUQrOsEgU0mD0VkAKITSx5VPKDmYEh2HcyS8wKcYuIklilpK78fdIJAyUMYQHb5Gofvl2SQUjuk5tdLARpdoE1xVw5LJgsfIy/+qFU8vdHeiuHPTtRHsTr5InSqBMAO24CZtCAEgUoiWnIliebSWpsxY5do/ZYlIcOsKRez17r8YdcCbHSeyC+Tv8UHCvqVyilYdL1pwfISwYuTNN3t5VpuWglnkiHIcfk8GbEh2PxWqX6kxID63vaebYk6RrVphVTUk9HRSbiToLh2T3TdbOF8sukWsX8HahWWhxyiMzRffsUzwFhpi7eC+gOxIPigzOvpjsWZzUxrWtVbGRkxkW9nsmNX4wMcLZj8msKqIo3okg6/YPzEn5IBC3ACxPzXH1MlBvrZK0OSW0AVgXd1Ca5LpCxU2IXDjgzNMFV2W48z3qTY7uoRTE2FUz+mt5nmZTHmhZtLkobJ1PRQ66Ui/f/cpoiL1y/WWfIJ9HfG94AUoLQK1+RpR1g+VY1sa2rJNnTU24hQWc7n5uZZDBDsBgY148pooYuChLeXHhn3KUJClhwugmvb5Hl2b6VnlbBIOp63qZBDg0wTejxe/8WuZZ4SItLaScr9dv+rMR1r1OI77rnnB6Bq2Rjr7NZBW0XtAf1m5fgf4M="
  secret_access_key:
    secure: "QdlzwOAxoW62US5RnqPzi9Sxn5PbNlMQzgC+LbzXmuYmtyk38sHmrt2+9HELqBTX2PphUrGiaQ4MkSqlDnwtd1lxO4Tn+wdtBflXraLPVoecJouSXvKhPBHA4ZNXgi883YW1MOznQzR/Dybv1ftxZE/BgBqHo/Gp2zR4e2C2I3WSpjRYS11qx41Hmstf4vAm6UlXvmkZEsNtWP9ZZAQ1nSM6vKFwPs2Lp6uHidY6N0ILacZt1ArjVscLCiC2onEVMWdciNnt70dBSqb/CS1My1O9JboM41W8ARPJQCT26zIRe8ZBI11kdPI4UlXOnl6u6Y2gg79tnz08652QWIuGxJdkyJNmRxN6lLXaQC8uLH1ARc3GgV1nviU5uQwFhE1FduhvBxphjbGNitZ7KkxZ+tOaNlyxcqf0jN6veePaB7bd/TBAqiL1c6dfQ90Jw2TAA7R+SkNAL4AaK9oZ6vh+lWoOAkWZTlaklRi2iqNp7zW4elka4hJXw1PRqhhL0ie8rviu8ghWCdWpxM+lREqTV5b2FTwQqxvGBGjh5XRZhra+erliq8+cW9I0FqVGdg0SB4dkir6yr0YsVM+CV5ogj7U2lDtuMgKr99Lgizs/HkEXFBUFjp0Zfk0EZBKbC7hxcbzIyaYWlXGwYKRTcU3IaQx+jqk/ImhPqf8z1tvEnkg="
  region: eu-west-1
  app: crispy-spork
  env: staging
  bucket_name: elasticbeanstalk-eu-west-1-836966196605
